### ISSUE TITLE
QRegExp was deprecated in Qt 

### ISSUE THREAD

**Issue by joran2738** [wimdams/Device_finder#1]
QRegExp was deprecated in Qt and is no longer available in newer versions of Qt (starting from Qt 5). 

included "QRegularExpression.h"

changed "QRegExp" to "QRegularExpression"

from line 105 in mainwindow.cpp:
QRegularExpression  macRegExp("([0-9A-F]{2})[:-]([0-9A-F]{2})[:-]([0-9A-F]{2})[:-]([0-9A-F]{2})[:-]([0-9A-F]{2})[:-]([0-9A-F]{2})");
QRegularExpressionMatch match = macRegExp.match(msg.toUpper());
if(match.hasMatch()){
        QString foundOUI = match.captured(1) % match.captured(2) % match.captured(3);
        QString foundMAC = match.captured(0);

no more errors after this edit, not sure if it still works as intended.

**Comment by wimdams** [comment]
Dag Joran,

Dat klopt. QRegExp is inderdaad niet meer beschikbaar in Qt6.
Ik zal thuis eens kijken of het nog werkt zoals bedoeld.

Mvg,
Dams Wim

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
From: joran2738 ***@***.***>
Sent: Wednesday, November 8, 2023 12:24:18 PM
To: wimdams/Device_finder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wimdams/Device_finder] QRegExp was deprecated in Qt (Issue #1)


QRegExp was deprecated in Qt and is no longer available in newer versions of Qt (starting from Qt 5).

included "QRegularExpression.h"

changed "QRegExp" to "QRegularExpression"

from line 105 in mainwindow.cpp:
QRegularExpression macRegExp("([0-9A-F]{2}):-<%5B0-9A-F%5D%7B2%7D>:-<%5B0-9A-F%5D%7B2%7D>:-<%5B0-9A-F%5D%7B2%7D>:-<%5B0-9A-F%5D%7B2%7D>:-<%5B0-9A-F%5D%7B2%7D>");
QRegularExpressionMatch match = macRegExp.match(msg.toUpper());
if(match.hasMatch()){
QString foundOUI = match.captured(1) % match.captured(2) % match.captured(3);
QString foundMAC = match.captured(0);

no more errors after this edit, not sure if it still works as intended.

**Comment by wimdams** [comment]
The project now works in Qt6
